name: Create vcpkg export archive
on:
  workflow_dispatch:

permissions:
  contents: write

env:
  outputName: goldendict-ng-vcpkg-export

jobs:
  create_new_cache:
    runs-on: windows-11-arm
    steps:
      - uses: actions/checkout@v4
      - name: Create export
        run: |
          # Create directory manually to avoid "path not found" errors
          mkdir exports

          # ensure always up to date
          vcpkg x-update-baseline
  
          vcpkg install --x-feature=breakpad --allow-unsupported
          vcpkg export --zip --output-dir=.\exports --output=${{ env.outputName }} 
          ls .\exports

      - name: Upload as release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $vcpkgBaselineVersion = $(Get-Content .\vcpkg-configuration.json | ConvertFrom-Json).'default-registry'.'baseline'
          $dateString = Get-Date -Format "yyMMdd"
          
          $tagName = "vcpkg_${dateString}_${vcpkgBaselineVersion}"

          cd .\exports\
          $fileHash = $(Get-FileHash ${{ env.outputName }}.zip SHA512).Hash
          
          
          $notes=@"
          GoldenDict-ng's windows build artifacts created with vcpkg, for development purpose only.
          
          vcpkg baseline version: <https://github.com/microsoft/vcpkg/tree/${vcpkgBaselineVersion}>
          SHA512: 
          ``````
          ${fileHash}
          ``````
          packages:
          ``````
          "@
          Add-Content -Path .\note.txt  -Value ${notes}
          vcpkg list | Add-Content .\note.txt
          Add-Content -Path .\note.txt  -Value "``````"
          Get-Content .\note.txt
          
          
          gh release create "${tagName}" --notes-file=.\note.txt --title "vcpkg package export archive" --latest=false
          gh release upload "${tagName}" ${{ env.outputName }}.zip  --clobber