name: macos-homebrew-breakpad
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on: 
  workflow_dispatch:
  #push:
  #  branches:
  #    - dev
  #    - master
  #    # - staged
  #  paths-ignore:
  #    - 'docs/**'
  #    - ".github/**"
  #    - "howto/**"
  #    - "*.md"
  #    - ".clang-format"
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]
        qt_ver: [ 6.4.3,6.5.2 ]
        qt_arch: [clang_64]
    env:
      targetName: GoldenDict
      version: 23.07.23
      version-suffix: GreatHeat
      prerelease: false
    steps:
      # macos 11.0 ÈªòËÆ§ÁéØÂ¢ÉÂèò‰∫Ü,Ë¶ÅÊåáÂÆö
      - name: prepare env
        if: ${{ matrix.os == 'macos-11' }}
        run: |
          softwareupdate --all --install --force
          sudo xcode-select --print-path
          sudo xcode-select --switch /Library/Developer/CommandLineTools    
               
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Set outputs
        id: githash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"   
       
      - name: install deps on macos
        run: |
          brew install pcre2 harfbuzz freetype
          brew install cmake ninja python
          brew install automake
          brew install autoconf
          brew install libtool
          brew install opencc
          brew install speex
          brew install wavpack
          brew install automake fdk-aac git lame libass libtool libvorbis libvpx opus sdl shtool texi2html theora wget x264 x265 xvid nasm
          brew install speex
          
          brew tap homebrew-ffmpeg/ffmpeg
          brew install homebrew-ffmpeg/ffmpeg/ffmpeg --with-speex

          brew install libiconv
          brew install lzo bzip2
          brew install libogg
          brew install zstd lzip
          brew install libvorbis
          brew install hunspell
          git clone https://github.com/xiaoyifang/eb.git
          cd eb && ./configure && make -j 8 && sudo make install && cd ..
          brew install  xz lzo 
          brew install pkg-config
          brew install create-dmg
          brew install xapian
          brew install libzim
          # brew reinstall icu4c
          brew install dylibbundler
          find /opt -name libicudata.72.dylib 
          find /usr/local -name libicudata.72.dylib 
      - name: version-file
        shell: bash
        env:
          VAR_SUFFIX: ${{env.version-suffix}}
          VAR_VERSION: ${{env.version}}
        run: |   
          current_tag=$(git rev-parse --short=8 HEAD)
          release_date=$(date +'%Y%m%d')
          echo "$VAR_VERSION-$VAR_SUFFIX.$release_date.$current_tag">version.txt  
          cat version.txt
          echo "$version"        
          
      - name: vcpkg install
        shell: bash
        run: |   
          vcpkg install breakpad
      - name: copy vcpkg packages into winlibs
        shell: bash
        run: |   
          ls -al /usr/local/share/vcpkg/packages/breakpad*
          cp -R /usr/local/share/vcpkg/packages/breakpad*/*  thirdparty/breakpad
          ls -al thirdparty/breakpad/lib
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'              
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}
          
          modules: qtwebengine qtwebchannel qtpositioning qt5compat qtmultimedia qtimageformats qtspeech
          setup-python: 'false'
          
      - name: compile
        run: |          
          qmake CONFIG+=release CONFIG+=no_macos_universal CONFIG+=zim_support CONFIG+=use_xapian CONFIG+=use_breakpad
          make -j8
          
      - name: package
        run: |
          
          macdeployqt ${targetName}.app -no-strip -qmldir=. -verbose=1
          otool -L GoldenDict.app/Contents/MacOS/GoldenDict
          ls -al GoldenDict.app/Contents/Frameworks
          otool -L GoldenDict.app/Contents/Frameworks/libicu*.dylib
          ls -al /usr/local/Cellar/icu4c/7*/lib/libicudata.*.dylib
          cp -r /usr/local/Cellar/icu4c/7*/lib/libicudata.*.dylib  GoldenDict.app/Contents/Frameworks

          codesign --force --deep -s - GoldenDict.app
          
          ls -al GoldenDict.app/Contents/Frameworks
          mkdir tmp
          mv ${targetName}.app ./tmp
          # --background "installer_background.png"
          create-dmg --volname "${targetName} Installer" --volicon "icons/macicon.icns" --window-pos 200 120 --window-size 800 400 --icon-size 100 --icon "${targetName}.app" 200 190 --hide-extension "${targetName}.app" --app-drop-link 600 185 --skip-jenkins "${targetName}.dmg" tmp/
      - name: changelog
        id: changelog
        run: |   
          previousTag=$(git tag --sort=-creatordate | grep "^v" | grep -v "alpha"  | sed -n 2p)
          echo "previousTag : $previousTag"
          

          echo "::set-output name=prev_tag::$previousTag"
          echo "::set-output name=curr_tag::$(git tag --sort=-creatordate | grep "^v" | grep -v "alpha"  | sed -n 1p)"

      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short=8 HEAD)"    
          echo "::set-output name=release_date::$(date +'%Y%m%d')"    
          echo "::set-output name=release_time::$(date +'%H%M%S')"  
          echo "::set-output name=release_time_clock::$(date +'%H:%M:%S')"   
          echo "::set-output name=release_hm::$(date +'%y%m%d')"  

      # tag ‰∏ä‰º†Release
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          commitMode: false
          fromTag: ${{ steps.changelog.outputs.prev_tag }}
          toTag:  "${{ steps.changelog.outputs.curr_tag }}"  
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>üî¥ Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
              "categories": [
                {
                    "title": "## üöÄ Features",
                    "labels": ["feature","feat","opt"]
                },
                {
                    "title": "## üêõ Fixes",
                    "labels": ["fix","bug"]
                }
                ,
                {
                    "title": "##  ü§ñ  Github action",
                    "labels": ["action"]
                }
                ,
                {
                    "title": "##  üßº  Clean Code",
                    "labels": ["clean"]
                }

              ],
              "label_extractor": [
              {
                "pattern": "([^:]*):.*",
                "target": "$1",
                "on_property": "title",
                "flags": "gu"
              }
            ]
            }          
      - name: uploadRelease
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.targetName }}.dmg
          asset_name: ${{ matrix.qt_ver }}-${{ env.targetName }}_${{ matrix.os }}_homebrew_breakpad_${{steps.vars.outputs.release_date}}.dmg
          
          tag: v${{env.version}}-${{env.version-suffix}}.${{ steps.vars.outputs.sha_short }}
          overwrite: true
          release_name: GoldenDict-ng-v${{env.version}}-${{env.version-suffix}}.${{ steps.vars.outputs.release_hm }}.${{ steps.vars.outputs.sha_short }}
          prerelease: ${{env.prerelease}}
          body: |
            #### Install instructions for Windows, macOS and Linux 

            <https://xiaoyifang.github.io/goldendict-ng/install/>.

            #### Filename pattern (Êñá‰ª∂ÂêçÊ®°Âºè): **[Qt version]-GoldenDict-ng-[OS]-[release-date].[ext]**  

            Qt6.X is recommended for various enhancements.

            Windows users can use either `****-installer.exe` (for installer) or `****.zip` (unzip and run).
            The `goldendict.exe` can be dropped into previous installation's folder (if dependencies aren't changed).

            Linux users can use AppImages.

            macOS users can use `.dmg` installer.

            `6.5.1-GoldenDict.exe_windows-2019_20230701.zip` means built with Qt6.5.1, windows/msvc-2019 at 20230701 as a zip archive.

            #### Build Details

            AppImage: Ubuntu-20.04
            macOS: macOS-12 and macOS-13
            Windows: Visual studio 2019



            #### Changes
            
            ${{steps.build_changelog.outputs.changelog}}
